# Generated by Django 5.1.4 on 2026-05-17 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LightningWarningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="统计开始时间")),
                ("end_time", models.DateTimeField(verbose_name="统计结束时间")),
                (
                    "response_time",
                    models.DateTimeField(db_index=True, verbose_name="结果时次"),
                ),
                ("device_id", models.IntegerField(verbose_name="设备ID")),
                ("warning_type", models.IntegerField(verbose_name="预警等级")),
                ("max_val", models.IntegerField(verbose_name="最大值")),
                ("min_val", models.IntegerField(verbose_name="最小值")),
                ("avg_val", models.IntegerField(verbose_name="平均值")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
            ],
            options={
                "verbose_name": "雷电预警结果",
                "verbose_name_plural": "雷电预警结果",
                "db_table": "lightning_warning_result",
            },
        ),
        migrations.CreateModel(
            name="TAtmoConfigTj",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "device_code",
                    models.CharField(max_length=20, verbose_name="设备编码"),
                ),
                (
                    "device_name",
                    models.CharField(max_length=20, verbose_name="设备名称"),
                ),
                ("lng", models.FloatField(blank=True, null=True, verbose_name="经度")),
                ("lat", models.FloatField(blank=True, null=True, verbose_name="纬度")),
                ("height", models.IntegerField(default=0, verbose_name="高度")),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="县区"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(max_length=50, verbose_name="设备类型"),
                ),
                (
                    "append_data",
                    models.TextField(blank=True, null=True, verbose_name="附加数据"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "设备配置",
                "verbose_name_plural": "设备配置",
                "db_table": "t_atmo_config_tj",
            },
        ),
        migrations.CreateModel(
            name="TAtmoData",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
                (
                    "device_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="设备ID"
                    ),
                ),
                (
                    "mesaure_value",
                    models.FloatField(blank=True, null=True, verbose_name="测量值"),
                ),
                ("avg_value", models.FloatField(default=0, verbose_name="平均值")),
                ("rate", models.FloatField(default=0, verbose_name="比率")),
                ("warn", models.IntegerField(default=0, verbose_name="预警")),
            ],
            options={
                "verbose_name": "监测数据",
                "verbose_name_plural": "监测数据",
                "db_table": "t_atmo_data",
            },
        ),
    ]
