"""
Django settings for 1 project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab

import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
# apps 目录添加到 项目搜索包目录列表 即： sys.path 中
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'apps'))
# MUSIC Python SDK（cma.music）

_SRC = BASE_DIR / "src"
if _SRC.is_dir():
    sys.path.insert(0, str(_SRC))


def _env_bool(name, default=False):
    return str(os.getenv(name, str(default))).strip().lower() in ("1", "true", "yes", "on")


def _env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'p1fb97n@+mllxvqn=am76es0na20hqt%k66i-c&55o21fwtq3p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', '*')
CORS_ORIGIN_WHITELIST = (
    # 备注：允许源地址 `http://127.0.0.1:9999` 向当前 API 服务器发起跨域请求
    'http://127.0.0.1:9999',
    'http://localhost:8080',
)
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie
# Application definition
INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'users.apps.UserConfig',
    'nmc.apps.NmcConfig',
    "django_celery_beat",
    'reflectance.apps.ReflectanceConfig',
    'lightning_warning.apps.WarningConfig',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 最好添加至第一行
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# TODO: 修改包名
ROOT_URLCONF = 'Reflectance_api_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# TODO: 修改包名
WSGI_APPLICATION = 'Reflectance_api_service.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'leidian_warning'),
        'USER': os.getenv('MYSQL_USER', 'root'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'Flzxroot!'),
        'HOST': os.getenv('MYSQL_HOST', '17.18.0.5'),
        'PORT': os.getenv('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = False

USE_TZ = False

CORS_ORIGIN_ALLOW_ALL = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# AUTH_USER_MODEL = 'users.UserInfo'

REST_FRAMEWORK = {
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'django_filters.rest_framework.DjangoFilterBackend'
    # ],
    # TODO: 修改包名
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'light_api_service.utils.auth.TokenAuthenticate',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.AllowAny',
    ],
    # 自定义异常类
    # TODO: 修改包名
    'EXCEPTION_HANDLER': 'Reflectance_api_service.utils.custom_exception.custom_exception_handler',
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Access Token的有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh Token的有效期

}

# ... existing code ...
# Celery 配置
REDIS_HOST = os.getenv('REDIS_HOST', '192.168.30.90')
REDIS_PORT = os.getenv('REDIS_PORT', '30035')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', 'Flzxroot')
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1")

CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = False

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 5

CELERY_AUTO_START = int(_env_bool('CELERY_AUTO_START', True))

# 定时任务配置：每 5 分钟执行一次
CELERY_BEAT_SCHEDULE = {
    # "sync-weather-warning-every-5-minutes": {
    #     "task": "nmc.tasks.sync_weather_warning_task",
    #     "schedule": 300.0,
    # },
    "lightning-warning-every-6-minutes": {
        # 要执行的任务路径（模块.函数名）
        "task": "lightning_warning.celery_beat.tasks.run_lightning_warning_schedule_task",
        # 调度规则：每6分钟执行一次（在第0、6、12、18、24、30、36、42、48、54分钟触发）
        "schedule": crontab(minute="1-59/6"),
    },
    "reflectance-every-6-minutes": {
        "task": "reflectance.celery_beat.tasks.run_reflectance_schedule_task",
        "schedule": crontab(minute="1-59/6"),
    },
    "satellite-cloud-every-10-minutes": {
        "task": "nmc.tasks.sync_satellite_cloud_task",
        "schedule": crontab(minute="*/10"),
    },
    "cma-image-products-every-10-minutes": {
        "task": "nmc.tasks.sync_cma_image_products_task",
        "schedule": crontab(minute="*/10"),
    },
    # "precipitation-1h-every-6-minutes": {
    #     "task": "reflectance.celery_beat.tasks.run_precipitation_1h_schedule_task",
    #     "schedule": crontab(minute="1-59/6"),
    # },
    # "precipitation-3h-hourly": {
    #     "task": "reflectance.celery_beat.tasks.run_precipitation_3h_schedule_task",
    #     "schedule": crontab(minute="1"),
    # },
}

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, '../staticfiles'))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('DJANGO_MEDIA_ROOT', os.path.join(BASE_DIR, 'apps', '../apps/img', ))
