"""
Django settings for 1 project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# apps 目录添加到 项目搜索包目录列表 即： sys.path 中
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
# MUSIC Python SDK（cma.music）

_SRC = BASE_DIR / "src"
if _SRC.is_dir():
    sys.path.insert(0, str(_SRC))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p1fb97n@+mllxvqn=am76es0na20hqt%k66i-c&55o21fwtq3p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_WHITELIST = (
    # 备注：允许源地址 `http://127.0.0.1:9999` 向当前 API 服务器发起跨域请求
    'http://127.0.0.1:9999',
    'http://localhost:8080',
)
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie
# Application definition
INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'users.apps.UserConfig',
    'nmc.apps.NmcConfig',
    "django_celery_beat",
    'reflectance.apps.ReflectanceConfig',
    'lightning_warning.apps.WarningConfig',
    'report.apps.ReportConfig'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 最好添加至第一行
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# TODO: 修改包名
ROOT_URLCONF = 'Reflectance_api_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# TODO: 修改包名
WSGI_APPLICATION = 'Reflectance_api_service.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'leidian',       # 刚才创建的数据库名
        'USER': 'root',      # PostgreSQL 用户名
        'PASSWORD': '20001022',  # 安装时设置的密码
        'HOST': 'localhost',
        'PORT': '3306'         # PostgreSQL 默认端口

    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = False

USE_TZ = True

CORS_ORIGIN_ALLOW_ALL = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# AUTH_USER_MODEL = 'users.UserInfo'

REST_FRAMEWORK = {
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'django_filters.rest_framework.DjangoFilterBackend'
    # ],
    # TODO: 修改包名
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'light_api_service.utils.auth.TokenAuthenticate',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.AllowAny',
    ],
    # 自定义异常类
    # TODO: 修改包名
    'EXCEPTION_HANDLER': 'Reflectance_api_service.utils.custom_exception.custom_exception_handler',
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Access Token的有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh Token的有效期

}

# ... existing code ...
# Celery 配置
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"

CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = False

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 5

# 定时任务配置：每 5 分钟执行一次
CELERY_BEAT_SCHEDULE = {
    "sync-weather-warning-every-5-minutes": {
        "task": "nmc.tasks.sync_weather_warning_task",
        "schedule": 300.0,
    },
    "lightning-warning-every-6-minutes": {
        # 要执行的任务路径（模块.函数名）
        "task": "lightning_warning.celery_beat.tasks.run_lightning_warning_schedule_task",
        # 调度规则：每6分钟执行一次（在第0、6、12、18、24、30、36、42、48、54分钟触发）
        "schedule": crontab(minute="*/6"),
    },
}

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'apps', '../apps/img', )
